"""B7 pretrained drug embedding + biology-informed feature model.

B7 is designed as the first bridge from handcrafted molecular fingerprints to
paper-grade learned molecular representations. It expects a CSV of external
drug embeddings generated by a molecule encoder such as ChemBERTa, MolFormer,
Uni-Mol, or a comparable SMILES/3D encoder, then evaluates those embeddings
with expression PCA and pathway activity blocks under identical splits.
"""

from __future__ import annotations

import argparse
import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from mcdrp.features.drug_embeddings import (
    DrugEmbeddingTable,
    build_drug_embedding_matrix,
    load_drug_embeddings,
)
from mcdrp.features.expression import build_cell_features
from mcdrp.features.pathways import build_pathway_features
from mcdrp.metrics import regression_metrics
from mcdrp.models.ablation_b6 import feature_matrix_from_cell_map
from mcdrp.models.baseline_b2 import fit_xgboost, predict_xgboost, xgb_device_params
from mcdrp.splits.make_splits import DEFAULT_SPLITS

logger = logging.getLogger(__name__)

EXPRESSION_PATH = "data/raw/OmicsExpressionTPMLogp1HumanProteinCodingGenesStranded.csv"
DEFAULT_B7_MODELS = (
    "pretrained_drug",
    "pretrained_drug_expression_pca",
    "pretrained_drug_pathways",
    "pretrained_drug_expression_pca_pathways",
)


def assemble_b7_features(
    rows: pd.DataFrame,
    *,
    model_name: str,
    drug_embedding_map: dict[str, np.ndarray],
    pca_feature_map: dict[str, np.ndarray],
    pathway_feature_map: dict[str, np.ndarray],
    cohort_key_column: str,
    missing_embeddings: str,
) -> np.ndarray:
    """Assemble one B7 feature matrix for a split subset."""

    blocks: list[np.ndarray] = []
    if "pretrained_drug" in model_name:
        blocks.append(
            build_drug_embedding_matrix(
                rows,
                drug_embedding_map,
                cohort_key_column=cohort_key_column,
                missing=missing_embeddings,
            )
        )
    if "expression_pca" in model_name:
        blocks.append(feature_matrix_from_cell_map(rows, pca_feature_map))
    if "pathways" in model_name:
        blocks.append(feature_matrix_from_cell_map(rows, pathway_feature_map))

    if not blocks:
        raise ValueError(f"Unknown B7 model variant: {model_name}")
    return np.hstack(blocks).astype(np.float32)


def metric_row(
    model_name: str,
    split_name: str,
    subset: str,
    rows: pd.DataFrame,
    predictions: np.ndarray,
    target: str,
    *,
    n_features: int,
    fit_seconds: float,
    best_iteration: int,
    device: str,
) -> dict[str, Any]:
    """Create one metrics row."""

    metrics = regression_metrics(
        rows[target].to_numpy(),
        predictions,
        cell_keys=rows["depmap_id"].tolist(),
        drug_keys=rows["drug_id"].tolist(),
    )
    return {
        "model": model_name,
        "split_name": split_name,
        "subset": subset,
        "n_rows": int(len(rows)),
        "n_cell_lines": int(rows["depmap_id"].nunique()),
        "n_drugs": int(rows["drug_id"].nunique()),
        "n_features": int(n_features),
        "fit_seconds": float(fit_seconds),
        "best_iteration": int(best_iteration),
        "device": device,
        **metrics,
    }


def run_b7_for_split(
    cohort: pd.DataFrame,
    assignments: pd.DataFrame,
    embedding_table: DrugEmbeddingTable,
    pca_feature_map: dict[str, np.ndarray],
    pathway_feature_map: dict[str, np.ndarray],
    *,
    split_name: str,
    target: str,
    model_names: tuple[str, ...],
    xgb_params: dict[str, Any],
    device: str,
    cohort_key_column: str,
    missing_embeddings: str,
) -> list[dict[str, Any]]:
    """Run every B7 variant for one split."""

    data = cohort.merge(assignments, on="pair_id", how="inner", validate="one_to_one")
    subsets = {
        subset: data.loc[data["split"].eq(subset)].copy()
        for subset in ("train", "validation", "test")
    }

    results: list[dict[str, Any]] = []
    for model_name in model_names:
        x_train = assemble_b7_features(
            subsets["train"],
            model_name=model_name,
            drug_embedding_map=embedding_table.embedding_map,
            pca_feature_map=pca_feature_map,
            pathway_feature_map=pathway_feature_map,
            cohort_key_column=cohort_key_column,
            missing_embeddings=missing_embeddings,
        )
        x_val = assemble_b7_features(
            subsets["validation"],
            model_name=model_name,
            drug_embedding_map=embedding_table.embedding_map,
            pca_feature_map=pca_feature_map,
            pathway_feature_map=pathway_feature_map,
            cohort_key_column=cohort_key_column,
            missing_embeddings=missing_embeddings,
        )
        y_train = subsets["train"][target].to_numpy()
        y_val = subsets["validation"][target].to_numpy()

        logger.info(
            "B7 %s / %s — train=%s, validation=%s",
            split_name,
            model_name,
            x_train.shape,
            x_val.shape,
        )
        t0 = time.time()
        model, actual_device = fit_xgboost(
            xgb_params,
            x_train,
            y_train,
            x_val,
            y_val,
            device=device,
        )
        fit_seconds = time.time() - t0
        best_iteration = getattr(model, "best_iteration", xgb_params["n_estimators"] - 1)

        for subset in ("validation", "test"):
            rows = subsets[subset]
            x_subset = assemble_b7_features(
                rows,
                model_name=model_name,
                drug_embedding_map=embedding_table.embedding_map,
                pca_feature_map=pca_feature_map,
                pathway_feature_map=pathway_feature_map,
                cohort_key_column=cohort_key_column,
                missing_embeddings=missing_embeddings,
            )
            predictions = predict_xgboost(model, x_subset)
            results.append(
                metric_row(
                    model_name,
                    split_name,
                    subset,
                    rows,
                    predictions,
                    target,
                    n_features=x_subset.shape[1],
                    fit_seconds=fit_seconds,
                    best_iteration=best_iteration,
                    device=actual_device,
                )
            )
    return results


def run_b7_pretrained(
    cohort_path: str | Path = "data/processed/cohort_pairs.csv",
    split_dir: str | Path = "data/processed/splits",
    expression_path: str | Path = EXPRESSION_PATH,
    drug_embeddings: str | Path = "data/external/drug_embeddings.csv",
    output: str | Path = "results/models/b7_pretrained_drug_pathway_metrics.csv",
    summary: str | Path = "data/reports/b7_pretrained_drug_pathway_summary.json",
    *,
    target: str = "ln_ic50",
    n_components: int = 256,
    gene_sets: str = "builtin_cancer_core",
    min_pathway_genes: int = 3,
    split_names: tuple[str, ...] = DEFAULT_SPLITS,
    model_names: tuple[str, ...] = DEFAULT_B7_MODELS,
    embedding_key_column: str = "drug_id",
    cohort_key_column: str = "drug_id",
    embedding_prefix: str | None = None,
    missing_embeddings: str = "error",
    n_estimators: int = 800,
    learning_rate: float = 0.025,
    max_depth: int = 5,
    early_stopping_rounds: int = 50,
    device: str = "auto",
) -> pd.DataFrame:
    """Run B7 pretrained embedding experiments."""

    cohort = pd.read_csv(cohort_path)
    split_dir = Path(split_dir)
    embedding_table = load_drug_embeddings(
        drug_embeddings,
        key_column=embedding_key_column,
        embedding_prefix=embedding_prefix,
    )
    logger.info(
        "Loaded %d drug embeddings with dimension %d from %s.",
        embedding_table.n_drugs,
        embedding_table.embedding_dim,
        embedding_table.source_path,
    )

    xgb_params: dict[str, Any] = {
        "n_estimators": n_estimators,
        "learning_rate": learning_rate,
        "max_depth": max_depth,
        "early_stopping_rounds": early_stopping_rounds,
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "tree_method": "hist",
        "random_state": 42,
        "n_jobs": -1,
    }
    xgb_params.update(xgb_device_params(device))

    all_results: list[dict[str, Any]] = []
    pathway_names: list[str] = []
    pca_variance_by_split: dict[str, float] = {}

    for split_name in split_names:
        logger.info("=== Processing B7 split: %s ===", split_name)
        assignments = pd.read_csv(split_dir / f"{split_name}.csv")
        merged = cohort.merge(assignments, on="pair_id", how="inner")
        train_ids = set(merged.loc[merged["split"].eq("train"), "depmap_id"].unique())

        pca_pipeline, pca_feature_map = build_cell_features(
            str(expression_path),
            cohort,
            train_ids,
            n_components=n_components,
        )
        pathway_pipeline, pathway_feature_map = build_pathway_features(
            str(expression_path),
            cohort,
            train_ids,
            gene_sets=gene_sets,
            min_genes=min_pathway_genes,
        )
        pathway_names = pathway_pipeline.pathway_names
        pca_variance_by_split[split_name] = float(
            pca_pipeline.explained_variance_ratio_sum
        )
        logger.info(
            "B7 %s — PCA variance %.1f%%, pathways=%d",
            split_name,
            pca_pipeline.explained_variance_ratio_sum * 100,
            len(pathway_names),
        )

        all_results.extend(
            run_b7_for_split(
                cohort,
                assignments,
                embedding_table,
                pca_feature_map,
                pathway_feature_map,
                split_name=split_name,
                target=target,
                model_names=model_names,
                xgb_params=xgb_params,
                device=device,
                cohort_key_column=cohort_key_column,
                missing_embeddings=missing_embeddings,
            )
        )

    metrics = pd.DataFrame(all_results)
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    metrics.to_csv(output_path, index=False)

    summary_data = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "cohort_path": str(cohort_path),
        "expression_path": str(expression_path),
        "split_dir": str(split_dir),
        "drug_embeddings": embedding_table.source_path,
        "output": str(output),
        "target": target,
        "embedding_key_column": embedding_key_column,
        "cohort_key_column": cohort_key_column,
        "embedding_dim": embedding_table.embedding_dim,
        "n_embedding_drugs": embedding_table.n_drugs,
        "embedding_columns": list(embedding_table.embedding_columns),
        "missing_embeddings": missing_embeddings,
        "n_pca_components": n_components,
        "pca_variance_by_split": pca_variance_by_split,
        "gene_sets": str(gene_sets),
        "min_pathway_genes": min_pathway_genes,
        "pathways": pathway_names,
        "model_variants": list(model_names),
        "xgb_params": {k: v for k, v in xgb_params.items() if k != "n_jobs"},
        "device_requested": device,
        "splits": list(split_names),
        "best_by_split_subset": summarize_best(metrics),
    }
    summary_path = Path(summary)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with summary_path.open("w", encoding="utf-8") as handle:
        json.dump(summary_data, handle, indent=2)
    return metrics


def summarize_best(metrics: pd.DataFrame) -> list[dict[str, Any]]:
    """Summarize the best B7 variant for each split/subset."""

    rows: list[dict[str, Any]] = []
    for (split_name, subset), group in metrics.groupby(["split_name", "subset"]):
        best = group.sort_values("rmse").iloc[0]
        rows.append(
            {
                "split_name": split_name,
                "subset": subset,
                "best_model": best["model"],
                "rmse": float(best["rmse"]),
                "mae": float(best["mae"]),
                "pearson": float(best["pearson"])
                if pd.notna(best["pearson"])
                else None,
                "spearman": float(best["spearman"])
                if pd.notna(best["spearman"])
                else None,
                "r2": float(best["r2"]) if pd.notna(best["r2"]) else None,
            }
        )
    return rows


def build_parser() -> argparse.ArgumentParser:
    """Create the command-line parser."""

    parser = argparse.ArgumentParser(
        description="Run B7 pretrained drug embedding experiments."
    )
    parser.add_argument("--cohort", default="data/processed/cohort_pairs.csv")
    parser.add_argument("--split-dir", default="data/processed/splits")
    parser.add_argument("--expression", default=EXPRESSION_PATH)
    parser.add_argument(
        "--drug-embeddings",
        default="data/external/drug_embeddings.csv",
        help="CSV with external drug embeddings.",
    )
    parser.add_argument(
        "--output",
        default="results/models/b7_pretrained_drug_pathway_metrics.csv",
    )
    parser.add_argument(
        "--summary",
        default="data/reports/b7_pretrained_drug_pathway_summary.json",
    )
    parser.add_argument("--target", default="ln_ic50")
    parser.add_argument("--n-components", type=int, default=256)
    parser.add_argument("--gene-sets", default="builtin_cancer_core")
    parser.add_argument("--min-pathway-genes", type=int, default=3)
    parser.add_argument(
        "--embedding-key-column",
        default="drug_id",
        help="Key column in the embedding CSV.",
    )
    parser.add_argument(
        "--cohort-key-column",
        default="drug_id",
        help="Column in cohort rows used to look up embeddings.",
    )
    parser.add_argument(
        "--embedding-prefix",
        default=None,
        help="Optional prefix used to select embedding columns, e.g. emb_.",
    )
    parser.add_argument(
        "--missing-embeddings",
        choices=["error", "zero"],
        default="error",
        help="How to handle cohort drugs missing from the embedding table.",
    )
    parser.add_argument("--n-estimators", type=int, default=800)
    parser.add_argument("--learning-rate", type=float, default=0.025)
    parser.add_argument("--max-depth", type=int, default=5)
    parser.add_argument("--early-stopping-rounds", type=int, default=50)
    parser.add_argument("--device", choices=["auto", "cuda", "cpu"], default="auto")
    parser.add_argument(
        "--splits",
        nargs="+",
        default=list(DEFAULT_SPLITS),
        choices=list(DEFAULT_SPLITS),
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=list(DEFAULT_B7_MODELS),
        choices=list(DEFAULT_B7_MODELS),
    )
    return parser


def main() -> None:
    """Command-line entry point."""

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s: %(message)s",
    )
    args = build_parser().parse_args()
    metrics = run_b7_pretrained(
        cohort_path=args.cohort,
        split_dir=args.split_dir,
        expression_path=args.expression,
        drug_embeddings=args.drug_embeddings,
        output=args.output,
        summary=args.summary,
        target=args.target,
        n_components=args.n_components,
        gene_sets=args.gene_sets,
        min_pathway_genes=args.min_pathway_genes,
        split_names=tuple(args.splits),
        model_names=tuple(args.models),
        embedding_key_column=args.embedding_key_column,
        cohort_key_column=args.cohort_key_column,
        embedding_prefix=args.embedding_prefix,
        missing_embeddings=args.missing_embeddings,
        n_estimators=args.n_estimators,
        learning_rate=args.learning_rate,
        max_depth=args.max_depth,
        early_stopping_rounds=args.early_stopping_rounds,
        device=args.device,
    )
    print(f"\nWrote B7 pretrained metrics to {args.output}")
    print("=" * 72)
    for _, row in metrics.sort_values(["split_name", "subset", "rmse"]).iterrows():
        print(
            f"  {row['split_name']:>14s} / {row['subset']:>10s} / "
            f"{row['model']:>38s}: RMSE={row['rmse']:.3f}  "
            f"MAE={row['mae']:.3f}  Pearson={row['pearson']:.3f}  "
            f"R²={row['r2']:.3f}"
        )


if __name__ == "__main__":
    main()
